<?php

$base_file = __DIR__ . '/../mediacommons_base_import/' . 'mediacommons_base_import.module';

function mediacommons_imr_import_init() {

  $commands = array(
    array(
      'label' => t('Import IMR D6 Content (all the stepts)'),
      'callback' => array(
        'mediacommons_base_import_generate_vocabulary',
        'mediacommons_base_import_generate_terms',   
        'mediacommons_base_import_generate_roles',             
        'mediacommons_base_import_generate_all_users',
      ),
    ),
    array(
      'label' => t('Migrate posts'),
      'callback' => array(
        'mediacommons_imr_import_migrate_posts',
      ),
    ),
    array(
      'label' => t('Migrate Theme Weeks'),
      'callback' => array(
        'mediacommons_imr_import_migrate_theme_weeks'
      ),
    ),
    array(
      'label' => t('Delete post and comments and file registry'),
      'callback' => array(
        'mediacommons_base_import_delete_comments',
        'mediacommons_base_import_delete_post',
        'mediacommons_base_import_delete_files',
      ),
    ),
    array(
      'label' => t('Run test'),
      'callback' => array(
        'mediacommons_imr_import_test',
      ),
    ),    
    
  );

  mediacommons_base_import_init(
    array('commands' => $commands)
  );

}

if (file_exists($base_file)) {
  include_once($base_file);
  mediacommons_imr_import_init();
}