; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[auto_nodetitle][version] = "1.0"

projects[ctools][version] = "1.3"

projects[context][version] = "3.0-beta7"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[email][version] = "1.2"

projects[entity][version] = "1.2"

projects[features_extra][version] = "1.0-beta1"

projects[features][version] = "2.0-rc3"

projects[media][version] = "1.3"

projects[libraries][version] = "2.1"

projects[media_youtube][version] = "2.0-rc3"

projects[google_fonts][version] = "2.3"

projects[jquery_update][version] = "2.3"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[styleguide][version] = "1.1"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[cnr][version] = "4.22"

projects[imagefield_crop][version] = "2.0"

projects[libraries][version] = "2.1"

projects[references][version] = "2.1"

projects[video_embed_field][version] = "2.0-beta5"

projects[views][version] = "3.7"

; Themes

projects[rubik][version] = "4.0-beta9"

projects[tao][version] = "3.0-beta4"

; Others

projects[mediacommons_editorialworkflow][download][type] = "local"
projects[mediacommons_editorialworkflow][download][source] = lib/modules/mediacommons_editorialworkflow
projects[mediacommons_editorialworkflow][type] = "module"

projects[imagefield_crop_extended][download][type] = "local"
projects[imagefield_crop_extended][download][source] = lib/modules/imagefield_crop_extended
projects[imagefield_crop_extended][type] = "module"

projects[mediacommons_base][download][type] = "local"
projects[mediacommons_base][download][source] = lib/themes/mediacommons_base
projects[mediacommons_base][type] = "theme"

projects[mediacommons_profile][type] = "profile"
projects[mediacommons_profile][download][type] = "local"
projects[mediacommons_profile][download][source] = lib/profiles/mediacommons_profile