; This file was auto-generated by drush make
core = 7.x

api = 2

projects[drupal][version] = "7.34"

; Modules

projects[ctools][version] = "1.5"
projects[cnr][version] = "4.22"
projects[date][version] = "2.8"
projects[diff][version] = "3.2"
projects[ds][version] = "2.7"
projects[entity][version] = "1.5"
projects[features_extra][version] = "1.0-beta1"
projects[features][version] = "2.2"
projects[flexslider][version] = "2.0-alpha3"
projects[imagefield_crop][version] = "1.1"
projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[menu_token][version] = "1.0-beta5"
projects[references][version] = "2.1"
projects[nodequeue][version] = "2.0-beta1"
projects[pathauto][version] = "1.2"
projects[realname][version] = "1.2"
projects[strongarm][version] = "2.0"
projects[token][version] = "1.5"
projects[views][version] = "3.8"
projects[admin_menu][version] = "3.0-rc4"
projects[field_group][version] = "1.4"
projects[devel][version] = "1.5"

projects[mediacommons_modules][type] = "module"
projects[mediacommons_modules][download][type] = "git"
projects[mediacommons_modules][download][url] = "https://github.com/NYULibraries/mediacommons_modules.git"

projects[mediacommons_profile][type] = "profile"
projects[mediacommons_profile][download][type] = "git"
projects[mediacommons_profile][download][url] = "https://github.com/NYULibraries/mediacommons_profile.git"

; Themes

projects[rubik][version] = "4.1"
projects[tao][version] = "3.1"
projects[zen][version] = "5.5"

projects[mediacommons][download][type] = "git"
projects[mediacommons][download][url] = "https://github.com/lhenze/mediacommons.git"
projects[mediacommons][type] = "theme"

; Libraries

libraries[Mobile_Detect][download][type] = "git"
libraries[Mobile_Detect][download][url] = "https://github.com/serbanghita/Mobile-Detect.git"
libraries[Mobile_Detect][directory_name] = "Mobile_Detect"
libraries[Mobile_Detect][type] = "library"

libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"
