<?php

function init () {
  $commands = array(
    array(
      'label' => t('Migrate site'),
      'callback' => array (
        /**
         * We no longer locally run the tasks:
         *   - mediacommons_base_import_generate_vocabulary
         *   - mediacommons_base_import_generate_terms
         *   - mediacommons_base_import_map_roles
         *   - mediacommons_base_import_generate_all_users
         *         
         * Terms are migrated and dealt with at the Umbrealla site
         *
         * @TODO: add a task to test if we can reach Umbrella?
         *
         */
      	'mediacommons_base_import_prepare_taxonomy_fields',
      	'mediacommons_base_import_download_files', // download files that are managed by Drupal
      	'download_image_attach_files', // download all image attach files that are managed by Drupal
      	'migrate_pages',
      	'migrate_contributed_pieces',
        'migrate_clusters',
        'migrate_responses',
      ),
    ),
  );
  mediacommons_base_import_init ( array ( 'commands' => $commands ) ) ;
}

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module' ;

if (!file_exists($base_file)) exit(drush_set_error(dt('Unable to find "@file".', array('@file' => $base_file))));

include_once($base_file);

init();
