<?php

function init () {
  $commands = array(
    array(
      'label' => t('Migrate site'),
      'callback' => array(
        'setup_project_environment', // Project should declare this callback. See *.project.inc
      	'download_files',
      	'download_image_attach_files',
      	'migrate_pages',
      	'migrate_contributed_pieces',
        'migrate_clusters',
        'migrate_responses',
        'enable_devel_options', // https://jira.nyu.edu/jira/browse/MC-262
        'enable_twitter_block', // https://jira.nyu.edu/jira/browse/MC-319
        'config_apachesolr',
        'config_recaptcha', // https://jira.nyu.edu/jira/browse/MC-281
        'node_access_rebuild',        
        'cache_clear_all',  // flush cache
        'drupal_flush_all_caches',
        'drupal_cron_run',
      ),
    ),
  );  
  mediacommons_base_import_init(array('commands' => $commands));
}

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module';

if (!file_exists($base_file)) exit(drush_set_error(dt('Unable to find "@file".', array('@file' => $base_file))));

include_once($base_file);

init();
