<?php

$base_file = __DIR__ . '/../mediacommons_base_import/' . 'mediacommons_base_import.module';

function mediacommons_imr_import_init() {

  $commands = array(
    array(
      'label' => t('Import IMR D6 Content'),
      'callback' => array(
        'mediacommons_base_import_generate_vocabulary',
        'mediacommons_base_import_generate_terms',   
        'mediacommons_base_import_generate_roles',             
        'mediacommons_base_import_generate_all_users',
        'mediacommons_imr_import_migrate_posts',
        'mediacommons_imr_import_migrate_theme_weeks',        
      ),
    ),
    array(
      'label' => t('Migrate posts'),
      'callback' => array(
        'mediacommons_imr_import_migrate_posts',
      ),
    ),
    array(
      'label' => t('Migrate Theme Weeks'),
      'callback' => array(
        'mediacommons_imr_import_migrate_theme_weeks',
      ),
    ),
    array(
      'label' => t('Delete Theme Weeks, Posts, comments and file registry'),
      'callback' => array(
        'mediacommons_base_import_delete_post',
        'mediacommons_base_import_delete_hubs',
        'mediacommons_base_import_delete_comments',        
        'mediacommons_base_import_delete_files',
        'mediacommons_base_import_delete_alias'
      ),
    ),
    array(
      'label' => t('Echo 5 random Hubs URL'),
      'callback' => array(
        'mediacommons_imr_import_test_content',
      ),
    ),    
    array(
      'label' => t('Run test'),
      'callback' => array(
        'mediacommons_base_import_delete_hubs',
      ),
    ),    
    
  );

  mediacommons_base_import_init(
    array('commands' => $commands)
  );

}

if (file_exists($base_file)) {
  include_once($base_file);
  mediacommons_imr_import_init();
}