<?php

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module';

function mediacommons_imr_import_init() {

  $commands = array(
    array(
      'label' => t('Import IMR D6 Content'),
      'callback' => array(
        'mediacommons_base_import_generate_vocabulary',
        'mediacommons_base_import_generate_terms',
        'mediacommons_base_import_generate_roles',
      	'mediacommons_base_import_prepare_taxonomy_fields',
        'mediacommons_base_import_generate_all_users',
      	'mediacommons_base_import_migrate_user_realname',
      	'mediacommons_base_import_migrate_profile_fields',
        'mediacommons_imr_import_add_allowed_iframe_sources',
        'mediacommons_imr_import_migrate_posts',
        'mediacommons_imr_import_migrate_theme_weeks',
      ),
    ),
    array(
      'label' => t('Migrate posts'),
      'callback' => array(
        'mediacommons_imr_import_migrate_posts',
      ),
    ),
    array(
      'label' => t('Migrate Theme Weeks'),
      'callback' => array(
        'mediacommons_imr_import_migrate_theme_weeks',
      ),
    ),
  	array(
  	  'label' => t('Delete Theme Weeks, Posts'),
  	    'callback' => array(
  		  'mediacommons_base_import_delete_post',
  		  'mediacommons_base_import_delete_hubs',
          'mediacommons_base_import_delete_comments',
      ),
    ),
    array(
      'label' => t('Delete Theme Weeks, Posts, comments and file registry'),
      'callback' => array(
        'mediacommons_base_import_delete_post',
        'mediacommons_base_import_delete_hubs',
        'mediacommons_base_import_delete_comments',
        'mediacommons_base_import_delete_files',
        'mediacommons_base_import_delete_alias'
      ),
    ),

  );

  mediacommons_base_import_init( array ( 'commands' => $commands ) );

}

if ( file_exists ( $base_file ) ) {
  include_once ( $base_file );
  mediacommons_imr_import_init();
}