<?php

function init() {
  $commands = array(
    array(
      'label' => t('Migrate site'),
      'callback' => array(
      	'download_files', // download files that are managed by Drupal
      	'migrate_pages',
        'mediacommons_imr_import_MC151', // See: https://jira.nyu.edu/browse/MC-151
        'migrate_posts',
      	'migrate_theme_weeks',
        'enable_devel_options', // https://jira.nyu.edu/jira/browse/MC-262
      ),
    ),
  );
  mediacommons_base_import_init(array('commands' => $commands));
}

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module';

if (!file_exists($base_file)) exit(drush_set_error(dt('Unable to find "@file".', array('@file' => $base_file))));

include_once($base_file);

init();
