<?php

function init () {

  $commands = array (

    array (
  	  'label' => t('Migrate survey content'),
  		'callback' => array (
      	'mediacommons_base_import_generate_vocabulary',
      	'mediacommons_base_import_generate_terms',
      	'mediacommons_base_import_prepare_taxonomy_fields',
      	'mediacommons_base_import_map_roles',
      	'mediacommons_base_import_download_files',
      	'mediacommons_base_import_generate_all_users',
        'migrate_survey_questions',
        'migrate_survey_responses',
        'response_arrange_order',
      	// 'mediacommons_fieldguide_import_body_field', // find <embed> and <object> and convert them into <iframe>        
  	  ) ,
    ) ,
    
    array (
  	  'label' => t('Survey response arrange order'),
  		'callback' => array ( 'response_arrange_order' )
    )
    
  ) ;

  mediacommons_base_import_init ( array ( 'commands' => $commands ) ) ;

}

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module' ;

if ( ! file_exists ( $base_file ) ) exit( drush_set_error ( dt ('Unable to find "@file".', array('@file' => $base_file ) ) ) ) ;

include_once ( $base_file ) ;

init() ;
