<?php

function init() {
  $commands = array(
    array(
      'label' => t('Migrate site'),
      'callback' => array(
        //'register_users_images',
     	//'download_files',
        //'migrate_survey_questions',
        //'migrate_survey_responses',
        //'response_arrange_order',
        //'JIRA_MC186',
        //'enable_devel_options', // https://jira.nyu.edu/jira/browse/MC-262
      ),
    )
  );
  mediacommons_base_import_init(array('commands' => $commands));
}

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module';

if (!file_exists($base_file)) exit(drush_set_error(dt('Unable to find "@file".', array('@file' => $base_file))));

include_once($base_file);

init();
