<?php

$base_file = __DIR__ . '/../mediacommons_base_import/mediacommons_base_import.module';

function mediacommons_survey_import_init() {

  $commands = array(

    array(
      'label' => t('Migrate MediaCommons Survey content'),
      'callback' => array(
        'mediacommons_base_import_generate_vocabulary',
        'mediacommons_base_import_generate_terms',
        'mediacommons_base_import_generate_roles',
        'mediacommons_base_import_generate_all_users',
        'mediacommons_survey_import_migrate_all_survey_question',
        'mediacommons_survey_import_migrate_all_survey_response',
      ),
    ),

    array(
  	  'label' => t('Migrate MediaCommons Survey Questions'),
  	  'callback' => array(
  		'mediacommons_survey_import_migrate_all_survey_question',
  	  ),
    ),

  	array(
  	  'label' => t('Migrate MediaCommons Survey Response'),
  	  'callback' => array(
  		'mediacommons_survey_import_migrate_all_survey_response',
  	  ),
    ),

    array(
      'label' => t('Delete all nodes and files'),
      'callback' => array(
        'mediacommons_base_import_delete_hubs',
        'mediacommons_base_import_delete_post',
        'mediacommons_base_import_delete_comments',
        'mediacommons_base_import_delete_files',
      ),
    ),

  );

  mediacommons_base_import_init( array('commands' => $commands ) );

}

if ( file_exists($base_file) ) {
  include_once($base_file);
  mediacommons_survey_import_init();
}